server {
    listen 80; # Listen for traffic on port 80

    location / {
        root /usr/share/nginx/html; 
        index index.html index.htm;
        
        # If a user visits /dashboard, Nginx looks for a file called 'dashboard'. 
        # It won't find it! This line says: "If you don't find it, just 
        # give them index.html and let the React Router handle it."
        try_files $uri $uri/ /index.html;
    }
}